// Type declarations for @liquicode/jsonstor-elasticsearch
//
// Generated by jsonstor-docs/build/build-adapter-docs.js from docs/data/adapters.js.
// Edits here are erased by the next build.
//
// Documents are stored on an Elasticsearch or OpenSearch server.

declare module '@liquicode/jsonstor-elasticsearch'
{

	//---------------------------------------------------------------------
	// The settings this adapter takes.

	export interface AdapterSettings
	{
		/** The name or address of the Elasticsearch or OpenSearch server. */
		Server: string;
		/** The service port of the server. Defaults to `9200`. */
		Port?: number;
		/** Reach the server over `https` rather than `http`. There is no `TrustServerCertificate` beside it, because this adapter has no driver except the global `fetch`, which offers no supported way to relax certificate verification. Defaults to `false`. */
		Encrypt?: boolean;
		/** The index this storage reads and writes. It is the collection: one index holds one collection's documents. */
		IndexName: string;
		/** The document field which is the identifier. Its value becomes the Elasticsearch `_id`. `IdField` is the former spelling and still works. Defaults to `"_id"`. */
		PrimaryKey?: string;
		/** Allow an update or a replacement to change the identifier. Off by default, so an operation which would move it is refused by name rather than silently discarded. Defaults to `false`. */
		PrimaryKeyMutable?: boolean;
		/** The field which stores the document. It cannot be empty: Elasticsearch reserves `_id` as a metadata field, so a document carrying this family's default identifier field cannot be stored at the top level. See the notes. Defaults to `"jsonstor_document"`. */
		PayloadField?: string;
		/** The payload fields to give an explicit mapping, as `{ Name, Type }` and optionally `NullValue`. Only a mapped field can be searched on the server; everything else is stored, returned, and filtered by `jsongin`. See the notes. Defaults to `[]`. */
		Mappings?: array;
		/** The user to connect as. Empty means none, which is what a server with security disabled expects. Defaults to `""`. */
		UserName?: string;
		/** That user's password. Empty means none. Defaults to `""`. */
		Password?: string;
	}


	//---------------------------------------------------------------------
	// The storage this adapter returns.
	//
	// Its members belong to jsonstor rather than to any adapter, so they are left open
	// here rather than restated - an adapter which described them would be describing
	// the storage interface, which is not its to describe.

	export interface Storage
	{
		[ MemberName: string ]: any;
	}


	//---------------------------------------------------------------------
	// The adapter itself. This is what `require()` returns, and what you hand to
	// `jsonstor.LoadPlugin()`.

	export interface StorageAdapter
	{
		/** `'jsonstor-elasticsearch'`. The package's bare name, which `Aliases` maps onto a prime. */
		AdapterName: string;
		AdapterDescription: string;
		GetAdapter( jsonstor: any, Settings: AdapterSettings ): Storage;
		/** This package's prime versions, each registering under its own name. */
		Adapters: StorageAdapter[];
		/** Every other name this package answers to, mapped to the prime it resolves to. */
		Aliases: { [ AliasName: string ]: string };
	}


	//---------------------------------------------------------------------
	// The default export is the adapter, and is what `require()` returns.

	const adapter: StorageAdapter;
	export default adapter;


	//---------------------------------------------------------------------
	// Named exports, matching src/jsonstor-elasticsearch.mjs one for one.

	export const AdapterName: string;
	export const AdapterDescription: string;
	export const GetAdapter: StorageAdapter[ 'GetAdapter' ];
	export const Adapters: StorageAdapter[ 'Adapters' ];
	export const Aliases: StorageAdapter[ 'Aliases' ];

}
